version: '3.8'

services:
  caddy:
    image: caddy:alpine
    container_name: caddy-portfolio
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./out:/usr/share/caddy:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
